name: uva
dataloader:
  batch_size: 32
  num_workers: 16
  persistent_workers: false
  pin_memory: true
  prefetch_factor: 2
  shuffle: true
val_dataloader:
  batch_size: 32
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 50
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  mixed_precision: fp16
  use_ucgm: false
  profile: false
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    monitor_key: test_mean_score
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 1
    mode: max
ema:
  _target_: unified_video_action.model.autoregressive.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
logging:
  group: null
  id: null
  mode: online
  name: train_uva_libero10
  project: debug
  resume: true
  tags:
  - train_uva_libero10
  - libero10
  - default
multi_run:
  run_dir: data/outputs/train_uva_libero10
  wandb_name_base: train_uva_libero10
task:
  name: libero10
  task_type: single_dataset
  task_modes: []
  shape_meta:
    image_resolution: 128
    action:
      shape:
      - 10
    obs:
      agentview_rgb:
        shape:
        - 3
        - 128
        - 128
        type: rgb
      language:
        shape:
        - 15
  shape_meta_env:
    image_resolution: 128
    action:
      shape:
      - 10
    obs:
      agentview_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
  dataset:
    _target_: unified_video_action.dataset.libero_replay_image_dataset.LiberoReplayImageDataset
    shape_meta:
      image_resolution: 128
      action:
        shape:
        - 10
      obs:
        agentview_rgb:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        language:
          shape:
          - 15
    abs_action: true
    dataset_path: data/libero_10
    language_emb_model: clip
    horizon: 32
    n_obs_steps: 16
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    use_cache: true
    val_ratio: 0.02
    data_aug: true
    normalizer_type: all
  env_runner:
    _target_: unified_video_action.env_runner.libero_image_runner.LiberoImageRunner
    dataset_path: data/libero_10
    abs_action: true
    crf: 22
    fps: 10
    max_steps: 500
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 16
    n_test: 3
    n_test_vis: 1
    n_train: 1
    n_train_vis: 1
    past_action: false
    render_obs_key: agentview_image
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    shape_meta:
      image_resolution: 128
      action:
        shape:
        - 10
      obs:
        agentview_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
model:
  _target_: unified_video_action.workspace.train_unified_video_action_workspace.TrainUnifiedVideoActionWorkspace
  policy:
    _target_: unified_video_action.policy.unified_video_action_policy.UnifiedVideoActionPolicy
    selected_training_mode: null
    debug: false
    n_action_steps: 8
    use_proprioception: null
    use_history_action: null
    action_mask_ratio: 0.5
    different_history_freq: null
    predict_wrist_img: null
    predict_proprioception: null
    shape_meta:
      image_resolution: 128
      action:
        shape:
        - 10
      obs:
        agentview_rgb:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        language:
          shape:
          - 15
    vae_model_params:
      autoencoder_path: pretrained_models/vae/kl16.ckpt
      ddconfig:
        vae_embed_dim: 16
        ch_mult:
        - 1
        - 1
        - 2
        - 2
        - 4
    autoregressive_model_params:
      pretrained_model_path: /store/real/shuang/diffusion_policy_checkpoints/libero_10_image/unified-act-autoregressive-cant-proj-dataaug10-clip-2/checkpoints/best.ckpt
      model_size: mar_base
      img_size: 256
      vae_stride: 16
      patch_size: 1
      vae_embed_dim: 16
      mask_ratio_min: 0.7
      label_drop_prob: 0.1
      attn_dropout: 0.1
      proj_dropout: 0.1
      diffloss_d: 6
      diffloss_w: 1024
      diffloss_act_d: 6
      diffloss_act_w: 1024
      num_sampling_steps: 'few'
      diffusion_batch_mul: 1
      grad_checkpointing: false
      num_iter: 1
      cfg: 1
      cfg_schedule: linear
      temperature: 0.95
      predict_video: true
      act_diff_training_steps: 1000
      act_diff_testing_steps: '100'
      use_ucgm: true
      token_pruning: false
    action_model_params:
      predict_action: true
      act_model_type: conv_ori
      n_experts: 8
    shift_action: true
    # optimizer:
    #   learning_rate: 0.0001
    #   weight_decay: 0.02
    #   betas:
    #   - 0.9
    #   - 0.95
    optimizer:
      learning_rate: 0.0001
      weight_decay: 0.0
      betas:
      - 0.9
      - 0.999
      
n_gpus: 1

payload: checkpoints/libero10.ckpt
freeze_submodules: true
